---
title: "data-cleaning"
author: "Graham Montgomery"
date: "2/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = FALSE, message = FALSE}
library(dplyr)
library(tidyr)
```

# Read in the data
```{r}
catch_original <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1", 
                               method = "libcurl"), stringsAsFactors = FALSE)

```

# Make data tidy

I in column chinook (row 401) should be a 1.

```{r}
catch_clean <- catch_original %>% 
    select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum) %>%
    mutate(Chinook = ifelse(Chinook == "I", 1, Chinook)) %>% 
    mutate(Chinook = as.integer(Chinook))
    
```

## Data QA 

Determine which values were converted to NA by as.numeric.

```{r}

i <- which(is.na(catch_clean$Chinook))

catch_original[i,]

```

## Convert to long format

```{r}

catch_long <- catch_clean %>%
    pivot_longer(cols = -c(Region, Year), 
                 names_to = "species",
                 values_to = "catch") %>%
    rename(catch_thousands = catch) %>% 
    mutate(catch = catch_thousands*1000)

```

# Summarize 

```{r}
mean_region <- catch_long %>% 
    group_by(Region, species) %>% 
    summarize(mean_catch = mean(catch))
```

#Filter for only sockeye species

```{r}

sockeye_catch <- catch_long %>% 
    filter(species == "Sockeye") %>% 
    group_by(Year) %>% 
    summarize(mean_catch = mean(catch)) %>% 
    arrange(desc(mean_catch))


```

# Join to other data

Read in the region definitions table

```{r}
region_defs <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.303.1", method = "libcurl"), stringsAsFactors = FALSE) %>% select(code, mgmtArea)

head(region_defs)

```

Join it to our main dataframe.
```{r}
catch_joined <- left_join(catch_long, region_defs,
                          by = c("Region" = "code"))

head(catch_joined)

```

## Separate and Unite examples

Using separate
```{r}
sites_df <- data.frame(site = c("HAW-101",
                                "HAW-103",
                                "OAH-320",
                                "OAH-219",
                                "MAI-039"),
                       stringsAsFactors = FALSE)

sites_df %>% 
  separate(site, c("island", "site_number"), "-")

```

Using unite

```{r}
dates_df <- data.frame(year = c("1930",
                                "1930",
                                "1930"),
                       month = c("12",
                                "12",
                                "12"),
                       day = c("14",
                               "15",
                               "16"),
                       stringsAsFactors = FALSE)

dates_df %>% 
  unite(date, year, month, day, sep = "-")

```



